# @package _global_
scene_gen:
  cfg_name: small-scenes
  scene_priors_type: detailed
  evolver_priors_nodes_from_scene: True
  object_move_ratio_per_step: 0.025
  add_or_remove_objs: False
  min_floors: 1
  max_floors: 1
  min_rooms: 3
  max_rooms: 3
  min_furniture: 6
  max_furniture: 6
  min_objects: 4
  max_objects: 4
  priors_noise: 0.2
  priors_sparsity_level: 0.2
  use_move_freq: True
  random_evolver: False
