# @package _global_
model_type: gcn
recurrent: True

node_embed_size: 64
edge_features: all
node_features: all
fuse_node_features: True
add_num_nodes: False
add_num_edges: False
use_edge_weights: False

psg_memorization_baseline: False
zero_priors_to_objects: False
